### ISSUE TITLE
Integrating my branch

### ISSUE THREAD

**Issue by The-Compiler** [akissinger/dodo#69]
This is mostly a note to myself - I decided to open it here to make things more discoverable, I hope that's okay!

For a while I've been running my [tco branch](https://github.com/akissinger/dodo/compare/master...The-Compiler:dodo:tco) and didn't find the time to nicely split all my changes into PRs and upstream them... Whoops! With some great recent changes by @laarmen and others, I'm now back on using `master`, so I should have some motivation to get those integrated :sweat_smile: 

Here is a list of commits in there - some of them are most likely already fixed in other ways at this point. Over the upcoming weeks, I'll try to look at those and cross them off here.

- [ ] [4516ae8](https://github.com/The-Compiler/dodo/commit/4516ae8) Use raw strings for regex patterns
- [x] [b8ff42c](https://github.com/The-Compiler/dodo/commit/b8ff42c) Handle missing gnupg module gracefully: **Better solution in #65**
- [ ] [bfc9d94](https://github.com/The-Compiler/dodo/commit/bfc9d94) Don't try to save PGP attachments
- [ ] [042a794](https://github.com/The-Compiler/dodo/commit/042a794) Handle UnicodeEncodeError when reading references
- [ ] [1660673](https://github.com/The-Compiler/dodo/commit/1660673) Show match count in title
- [ ] [034362c](https://github.com/The-Compiler/dodo/commit/034362c) Don't crash when gpg signing is aborted: **Might be fixed already by catching all exceptions while sending in 7fa69262d9c778eb39ecb4d15289ab88ee38d63b**
- [ ] [9390aef](https://github.com/The-Compiler/dodo/commit/9390aef) Fix add_header_line to preserve empty line: **Also see #50**
- [ ] [5c06daa](https://github.com/The-Compiler/dodo/commit/5c06daa) Don't crash when gpg signing is aborted
- [ ] [b489317](https://github.com/The-Compiler/dodo/commit/b489317) Use notmuch to get attachment contents
- [ ] [4986238](https://github.com/The-Compiler/dodo/commit/4986238) Fix opening links with target=_blank
- [ ] [efb2b8e](https://github.com/The-Compiler/dodo/commit/efb2b8e) Add tooltips for tags
- [ ] [8259b69](https://github.com/The-Compiler/dodo/commit/8259b69) Fix encoding for HTML view
- [ ] [28b89b4](https://github.com/The-Compiler/dodo/commit/28b89b4) WIP: show message ID
- [ ] [9ad575f](https://github.com/The-Compiler/dodo/commit/9ad575f) Update all columns correctly
- [ ] [ff09803](https://github.com/The-Compiler/dodo/commit/ff09803) Fix crash with signature without user ID: **Might be fixed already by catching all exceptions while sending in 7fa69262d9c778eb39ecb4d15289ab88ee38d63b**
- [ ] [627ec12](https://github.com/The-Compiler/dodo/commit/627ec12) search: Only update current index when tagging
- [ ] [830aefa](https://github.com/The-Compiler/dodo/commit/830aefa) Add settings.html_confirm_open_links_trusted_hosts
- [ ] [bbe577c](https://github.com/The-Compiler/dodo/commit/bbe577c) Implement per-tag color overrides
- [ ] [d8c3baa](https://github.com/The-Compiler/dodo/commit/d8c3baa) Fix crash on empty search

**Comment by The-Compiler** [comment]
Some more notes to myself for follow-up work:

- [ ] #71 will conflict with #76
- [ ] Review temp file handling and `os.remove`, probably can be done in a nicer way with context managers for some cases
- [ ] `gnupg.py` could use a custom `GnupgError` instead of just `raise Exception`

**Comment by The-Compiler** [comment]
First batch cleaned up and turned into PRs :sweat_smile: 

For the remaining changes, it's either:

- A bugfix for a bug I don't know how to trigger anymore (whoops...)
- Something that'll conflict too much with an already open PR, and I'll get back to once that's merged
- Not relevant anymore after the changes since merged to `master`

For the remaining bugfixes, I'll run without those commits myself for a while and hope I can trigger them again - but it's entirely possible they also got fixed in `master` already since.
